import threading

count1 = 0
count2 = 0

def sum_of_squares():
   """Thread 1: Computes the sum of squares from 1–50."""
   
   global count1
   squares = [i ** 2 for i in range(1, 51)]
   total = sum(squares)
   count1 = len(squares)  
   print(f"Sum of squares (1–50): {total}")
   print(f"Thread 1 generated {count1} results")

def prime_numbers():
   """Thread 2: Identifies all prime numbers between 1–20."""
   
   global count2
   primes = []
   for num in range(2, 21):
      is_prime = True
      for i in range(2, int(num ** 0.5) + 1):
         if num % i == 0:
            is_prime = False
            break
      if is_prime:
         primes.append(num)
   count2 = len(primes)  
   print(f"Prime numbers (1–20): {primes}")
   print(f"Thread 2 generated {count2} results")

def output_count():
   """Thread 3: Counts the results generated by the other two threads."""
   
   total_outputs = count1 + count2
   print(f"\nThread 3 - Total results from both threads: {total_outputs}")
   print(f"  - Thread 1 (sum of squares): {count1} values")
   print(f"  - Thread 2 (prime numbers): {count2} values")

if __name__ == "__main__":
   t1 = threading.Thread(target=sum_of_squares)
   t2 = threading.Thread(target=prime_numbers)
   t3 = threading.Thread(target=output_count)

   t1.start()
   t2.start()

   t1.join()
   t2.join()

   t3.start()
   t3.join()

   print("\nAll threads completed!")